ingress:
  enabled: ${do_ingress_enabled}
  annotations:
    kubernetes.io/ingress.class: ${do_ingress_class}
    cert-manager.io/cluster-issuer: ${do_ingress_cluster_issuer}
  hosts:
    - host: ${host}
      paths:
        - path: "/"
  tls:
    - secretName: ${host}-tls
      hosts:
        - ${host}
nodeSelector:
  ${nodeSelector}
